"""initial schema and source seed

Revision ID: 0001
Revises:
Create Date: 2026-10-05 14:26:04.231677
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SOURCES = [
    # name, type, domains, fetch_allowed, is_system  (data-model.md seed table)
    ("Manual", "manual", [], False, True),
    ("Job Bank", "job_board", ["jobbank.gc.ca"], True, False),
    ("GC Jobs", "job_board", ["emploisfp-psjobs.cfp-psc.gc.ca"], True, False),
    ("Eluta.ca", "job_board", ["eluta.ca"], True, False),
    ("CharityVillage", "job_board", ["charityvillage.com"], True, False),
    ("Greenhouse", "ats", ["boards.greenhouse.io", "job-boards.greenhouse.io"], True, False),
    ("Lever", "ats", ["jobs.lever.co"], True, False),
    ("Ashby", "ats", ["jobs.ashbyhq.com"], True, False),
    ("Workday", "ats", ["myworkdayjobs.com"], True, False),
    ("LinkedIn", "job_board", ["linkedin.com"], False, False),
    ("Indeed", "job_board", ["indeed.com", "ca.indeed.com"], False, False),
    ("Glassdoor", "job_board", ["glassdoor.com", "glassdoor.ca"], False, False),
    ("Workopolis", "job_board", ["workopolis.com"], False, False),
]


def _seed_sources() -> None:
    source = sa.table(
        "source",
        sa.column("name", sa.String),
        sa.column("type", sa.String),
        sa.column("domains", sa.JSON),
        sa.column("fetch_allowed", sa.Boolean),
        sa.column("enabled", sa.Boolean),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        source,
        [
            {
                "name": name,
                "type": type_,
                "domains": domains,
                "fetch_allowed": fetch,
                "enabled": True,
                "is_system": system,
            }
            for name, type_, domains, fetch, system in SOURCES
        ],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.create_index("ix_login_attempt_lookup", ["username", "ip", "at"], unique=False)

    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("fetch_allowed", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("last_login_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_account_username"), ["username"], unique=True)

    op.create_table(
        "sender_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("from_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reply_to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("smtp_host", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("smtp_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bcc_self", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "target_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("synonyms", sa.JSON(), nullable=False),
        sa.Column("include_keywords", sa.JSON(), nullable=False),
        sa.Column("exclude_keywords", sa.JSON(), nullable=False),
        sa.Column("seniority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("target_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_target_profile_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ux_profile_user_name", ["user_id", "name"], unique=True)

    op.create_table(
        "user_session",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("csrf_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("work_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salary_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("salary_period", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url_norm", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_title_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_found", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["target_profile.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_profile_id"), ["profile_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_source_id"), ["source_id"], unique=False)
        batch_op.create_index("ix_job_user_ct_key", ["user_id", "company_title_key"], unique=False)
        batch_op.create_index("ix_job_user_date_found", ["user_id", "date_found"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_job_user_status", ["user_id", "status"], unique=False)
        batch_op.create_index(
            "ux_job_user_url_norm",
            ["user_id", "url_norm"],
            unique=True,
            sqlite_where=sa.text("url_norm IS NOT NULL"),
        )

    op.create_table(
        "location_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("place", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("work_modes", sa.JSON(), nullable=False),
        sa.Column("salary_floor", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["target_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location_rule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_rule_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_job_id"), ["job_id"], unique=False)

    op.create_table(
        "follow_up",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("done_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("follow_up", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_follow_up_job_id"), ["job_id"], unique=False)

    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_note_job_id"), ["job_id"], unique=False)

    op.create_table(
        "status_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("to_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("effective_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("recorded_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("status_change", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_status_change_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###
    _seed_sources()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("status_change", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_change_job_id"))

    op.drop_table("status_change")
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_note_job_id"))

    op.drop_table("note")
    with op.batch_alter_table("follow_up", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_follow_up_job_id"))

    op.drop_table("follow_up")
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_job_id"))

    op.drop_table("contact")
    with op.batch_alter_table("location_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_rule_profile_id"))

    op.drop_table("location_rule")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ux_job_user_url_norm", sqlite_where=sa.text("url_norm IS NOT NULL"))
        batch_op.drop_index("ix_job_user_status")
        batch_op.drop_index(batch_op.f("ix_job_user_id"))
        batch_op.drop_index("ix_job_user_date_found")
        batch_op.drop_index("ix_job_user_ct_key")
        batch_op.drop_index(batch_op.f("ix_job_source_id"))
        batch_op.drop_index(batch_op.f("ix_job_profile_id"))

    op.drop_table("job")
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_session_user_id"))

    op.drop_table("user_session")
    with op.batch_alter_table("target_profile", schema=None) as batch_op:
        batch_op.drop_index("ux_profile_user_name")
        batch_op.drop_index(batch_op.f("ix_target_profile_user_id"))

    op.drop_table("target_profile")
    op.drop_table("sender_settings")
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_account_username"))

    op.drop_table("user_account")
    op.drop_table("source")
    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.drop_index("ix_login_attempt_lookup")

    op.drop_table("login_attempt")
    # ### end Alembic commands ###
