"""job mailbox

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 15:43:35.322788
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mailbox_folder_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("folder", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uidvalidity", sa.Integer(), nullable=False),
        sa.Column("last_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mailbox_folder_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mailbox_folder_state_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ux_folder_state", ["user_id", "folder"], unique=True)

    op.create_table(
        "mailbox_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imap_host", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imap_port", sa.Integer(), nullable=False),
        sa.Column("checking_enabled", sa.Boolean(), nullable=False),
        sa.Column("filing_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_check_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("last_result", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("address"),
    )
    op.create_table(
        "email_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dedupe_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("in_reply_to", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("references", sa.JSON(), nullable=False),
        sa.Column("from_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reply_to", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("to_addrs", sa.JSON(), nullable=False),
        sa.Column("cc_addrs", sa.JSON(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("body_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_storage_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("folder", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("folder_uid", sa.Integer(), nullable=True),
        sa.Column("moved_by_user", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("link_method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("send_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("send_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("saved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_message", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_message_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_message_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_message_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_email_user_job", ["user_id", "job_id"], unique=False)
        batch_op.create_index("ix_email_user_saved", ["user_id", "saved_at"], unique=False)
        batch_op.create_index("ux_email_user_dedupe", ["user_id", "dedupe_key"], unique=True)

    op.create_table(
        "email_attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["email_id"], ["email_message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_attachment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_attachment_email_id"), ["email_id"], unique=False
        )

    op.create_table(
        "job_suggestion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url_norm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["email_id"], ["email_message.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_suggestion_email_id"), ["email_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_suggestion_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_suggestion_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_suggestion_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ux_suggestion_user_url", ["user_id", "url_norm"], unique=True)

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("alert_sender", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###

    # Seed: these sites send job-alert emails (feature 002, FR-018).
    op.execute(
        "UPDATE source SET alert_sender = 1 WHERE name IN "
        "('LinkedIn', 'Indeed', 'Glassdoor', 'Job Bank', 'Eluta.ca', 'Workopolis')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("alert_sender")

    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.drop_index("ux_suggestion_user_url")
        batch_op.drop_index(batch_op.f("ix_job_suggestion_user_id"))
        batch_op.drop_index(batch_op.f("ix_job_suggestion_source_id"))
        batch_op.drop_index(batch_op.f("ix_job_suggestion_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_suggestion_email_id"))

    op.drop_table("job_suggestion")
    with op.batch_alter_table("email_attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_attachment_email_id"))

    op.drop_table("email_attachment")
    with op.batch_alter_table("email_message", schema=None) as batch_op:
        batch_op.drop_index("ux_email_user_dedupe")
        batch_op.drop_index("ix_email_user_saved")
        batch_op.drop_index("ix_email_user_job")
        batch_op.drop_index(batch_op.f("ix_email_message_user_id"))
        batch_op.drop_index(batch_op.f("ix_email_message_source_id"))
        batch_op.drop_index(batch_op.f("ix_email_message_job_id"))

    op.drop_table("email_message")
    op.drop_table("mailbox_settings")
    with op.batch_alter_table("mailbox_folder_state", schema=None) as batch_op:
        batch_op.drop_index("ux_folder_state")
        batch_op.drop_index(batch_op.f("ix_mailbox_folder_state_user_id"))

    op.drop_table("mailbox_folder_state")
    # ### end Alembic commands ###
