"""automatic search

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 16:10:01.812305
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trigger", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_run_user_id"), ["user_id"], unique=False)

    op.create_table(
        "watch_company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("board_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("board_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("board_host", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("board_site", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("imported", sa.Boolean(), nullable=False),
        sa.Column("discovery_done", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watch_company", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watch_company_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="alert"
            )
        )
        batch_op.add_column(sa.Column("watch_company_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("profile_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("salary_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("work_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("posted_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("score", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("score_reasons", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.create_index(
            batch_op.f("ix_job_suggestion_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_suggestion_watch_company_id"), ["watch_company_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_suggestion_watch_company",
            "watch_company",
            ["watch_company_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_suggestion_profile", "target_profile", ["profile_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###

    # Board APIs used by the company watchlist (feature 003) belong to these sources.
    for name, domain in (
        ("Greenhouse", "boards-api.greenhouse.io"),
        ("Lever", "api.lever.co"),
        ("Ashby", "api.ashbyhq.com"),
    ):
        op.execute(
            sa.text(
                "UPDATE source SET domains = json_insert(domains, '$[#]', :d) "
                "WHERE name = :n AND NOT EXISTS "
                "(SELECT 1 FROM json_each(source.domains) WHERE value = :d)"
            ).bindparams(d=domain, n=name)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.drop_constraint("fk_suggestion_watch_company", type_="foreignkey")
        batch_op.drop_constraint("fk_suggestion_profile", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_job_suggestion_watch_company_id"))
        batch_op.drop_index(batch_op.f("ix_job_suggestion_profile_id"))
        batch_op.drop_column("score_reasons")
        batch_op.drop_column("score")
        batch_op.drop_column("posted_at")
        batch_op.drop_column("work_mode")
        batch_op.drop_column("salary_text")
        batch_op.drop_column("description")
        batch_op.drop_column("profile_id")
        batch_op.drop_column("watch_company_id")
        batch_op.drop_column("origin")

    with op.batch_alter_table("watch_company", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_company_user_id"))

    op.drop_table("watch_company")
    with op.batch_alter_table("search_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_run_user_id"))

    op.drop_table("search_run")
    # ### end Alembic commands ###
