"""apply from app

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 17:22:55.386847
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "master_resume",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("source_resume_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_resume_id"], ["resume_file.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("master_resume", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_master_resume_source_resume_id"), ["source_resume_id"], unique=False
        )

    op.create_table(
        "document_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("ats_master", sa.Integer(), nullable=True),
        sa.Column("ats_tailored", sa.Integer(), nullable=True),
        sa.Column("resume_docx", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resume_pdf", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("letter_docx", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("letter_pdf", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_version_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_version_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tailored_resume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experience", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("cover_letter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tailored_resume", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tailored_resume_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tailored_resume_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ux_tailored_user_job", ["user_id", "job_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tailored_resume", schema=None) as batch_op:
        batch_op.drop_index("ux_tailored_user_job")
        batch_op.drop_index(batch_op.f("ix_tailored_resume_user_id"))
        batch_op.drop_index(batch_op.f("ix_tailored_resume_job_id"))

    op.drop_table("tailored_resume")
    with op.batch_alter_table("document_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_version_user_id"))
        batch_op.drop_index(batch_op.f("ix_document_version_job_id"))

    op.drop_table("document_version")
    with op.batch_alter_table("master_resume", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_resume_source_resume_id"))

    op.drop_table("master_resume")
    # ### end Alembic commands ###
