"""claude jobs

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 19:42:16.618610
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claude_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claude_job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claude_job_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fit_score", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("fit_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_suggestion", schema=None) as batch_op:
        batch_op.drop_column("fit_reason")
        batch_op.drop_column("fit_score")

    with op.batch_alter_table("claude_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claude_job_user_id"))

    op.drop_table("claude_job")
    # ### end Alembic commands ###
