"""reminders and prep

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 20:28:36.803781
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reminders_enabled", sa.Boolean(), nullable=False),
        sa.Column("stale_days", sa.Integer(), nullable=False),
        sa.Column("last_sent_on", sa.Date(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "job_prep",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_prep", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_prep_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_prep_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ux_job_prep_user_job", ["user_id", "job_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_prep", schema=None) as batch_op:
        batch_op.drop_index("ux_job_prep_user_job")
        batch_op.drop_index(batch_op.f("ix_job_prep_user_id"))
        batch_op.drop_index(batch_op.f("ix_job_prep_job_id"))

    op.drop_table("job_prep")
    op.drop_table("notification_settings")
    # ### end Alembic commands ###
